GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODAwOTk2ODF9.lcauksTQTyWvplHB5EPGl_PN9EM36c5oTaAb1xxNbU8

###

POST http://localhost:3000/login
Content-Type: application/json

{
	"username": "qwe"
}
