GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicXdlIiwiaWF0IjoxNTgwMTQ4NDEwLCJleHAiOjE1ODAxNDg0NTV9.hUnhj27pfQ9G6zDJ2vzsbJV7n2UtXsnpwyGqqAoxwpk

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicXdlIiwiaWF0IjoxNTgwMTQ4NDEwfQ.f-O0jk-4PhdOoPWGV0iKTDOgJS0Dwvs0TV0sqOQt6tg" 
}

###

POST  http://localhost:4000/token
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicXdlIiwiaWF0IjoxNTgwMTQ4NDEwfQ.f-O0jk-4PhdOoPWGV0iKTDOgJS0Dwvs0TV0sqOQt6tg"
	//refreshtoken, can refresh when we delete
}
###

POST http://localhost:4000/login
Content-Type: application/json

{
	"username": "qwe"
}
